### ISSUE TITLE
Binding autoexpand to custom/own textareas

### ISSUE THREAD

**Issue by FabienHenon** [ohanhi/autoexpand#4]
In my opinion, there should be a function to bind to our own textareas and its goal would be to change attributes, not to draw the textarea.

A use case I have is being able to use `autoexpand` with [https://github.com/debois/elm-mdl](elm-mdl) textareas.

I would like to use it like this:

```elm
Textfield.render Mdl [9] model.mdl
  ([ Textfield.label "Multiline with 6 rows"
  , Textfield.floatingLabel
  , Textfield.textarea
  , Textfield.value model.value
  ]
  ++ (List.map Options.attribute AutoExpand.autoExpand config model.state))
  []
```

There is maybe a better way of using it, but that's the idea.

We can keep `view` function and add another function that would return a list of `Attributes` (or we can rename the function `attrs` and expose it).

However, with the function returning a list of `Attributes` should we pass it the current value? Or handling it in our side? (I would say second option)

**Comment by ohanhi** [comment]
Okay, thanks. I will make a PR with a proposal soon, so you can take a look if it suits your needs.

**Comment by FabienHenon** [comment]
I can make the PR if you want (and don't have time)
